##############################################
# Configuration file for dcos-metrics service
# for Windows agent node
##############################################

  # Collector configuration
  collector:
    http_profiler: false

    node:
      poll_period: 60s

    mesos_agent:
      poll_period: 60s
      port: 5051
      request_protocol: http
      request_timeout: 30s

  # Producers configuration
  producers:
    # HTTP producer
    http:
      port: 9000